### ISSUE TITLE
Your Composer dependencies require a PHP version ">= 7.2.5" on watch.php

### ISSUE THREAD

**Issue by Magallanesmapping321** [pixdoet/yt-2005-watch#12]
Title says it all, any fix?

**Comment by pixdoet** [comment]
Simple, use php 7.3 or above :)

Also, you should probably consider upgrading to PHP 8, since the JIT compilation really works wonders with the homepage and stuff.

**Comment by Magallanesmapping321** [comment]
i guess.. my host server uses php 7.0
