### ISSUE TITLE
https://rehike.hiew.me/ got hacked

### ISSUE THREAD

**Issue by JoseErnestoOnGithub** [pixdoet/yt-2005-watch#24]
Pixdoet, it looks like your Dev website got hacked. It redirects to a McAfee scam.

See this picture:
![Screenshot 2023-04-10 114214](https://user-images.githubusercontent.com/115112109/230970888-e6ac5b5a-24a6-483e-9106-85f71891f6d0.png)

Please fix your Dev website as soon as possible. Your's truly, Jose Ernesto.

**Comment by JoseErnestoOnGithub** [comment]
It now got parked.
![Screenshot 2023-04-10 114823](https://user-images.githubusercontent.com/115112109/230971686-ad70fcfc-e7e3-4465-95a6-90d799cd1430.png)

**Comment by pixdoet** [comment]
Yeah hiew.me expired and I'm broke af to renew it

**Comment by JoseErnestoOnGithub** [comment]
OK.
