### ISSUE TITLE
Video playback doesn't seem to be working...?

### ISSUE THREAD

**Issue by wuxian425** [pixdoet/yt-2005-watch#25]
As in the title, the player does not seem to be able to load video resources correctly.
Test on Firefox 115.0.2 / K-Meleon 76.4.7.

![圖片](https://github.com/pixdoet/yt-2005-watch/assets/82699919/505b75ff-bf14-40a7-ad65-148c07381f0f)

**Comment by pixdoet** [comment]
Could be something to do with the way I get the video source, will tryna fix later

Also do you speak Chinese?

**Comment by wuxian425** [comment]
好的

Ian Hiew ***@***.***> 于 2023年7月22日周六 11:14写道：

**Comment by pixdoet** [comment]
fixed
